// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Receitas.Infra.Data;

namespace Receitas.Infra.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20211001175645_file")]
    partial class file
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Receitas.Domain.Services.ReceitaFotos.Entities.ReceitaFotosEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("File")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("IdReceita")
                        .HasColumnType("int");

                    b.Property<int?>("IdReceitasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdReceitasId");

                    b.ToTable("ReceitaFotos");
                });

            modelBuilder.Entity("Receitas.Domain.Services.Receitas.Entities.ReceitaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dificuldade")
                        .HasColumnType("int");

                    b.Property<double>("Horas")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Receitas");
                });

            modelBuilder.Entity("Receitas.Domain.Services.ReceitaFotos.Entities.ReceitaFotosEntity", b =>
                {
                    b.HasOne("Receitas.Domain.Services.Receitas.Entities.ReceitaEntity", "IdReceitas")
                        .WithMany()
                        .HasForeignKey("IdReceitasId");

                    b.Navigation("IdReceitas");
                });
#pragma warning restore 612, 618
        }
    }
}
